### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by y-yagi** [y-yagi/mokei#1]
* [x] raise error when can't determine target
* [ ] `target` is correct name?
* [x] add generator
* [x] support association
* [x] support `create`
* [x] explicitly specify the target
* [x] update readme
